modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
#issueTrackerURL = "${repository}/issues"

[[mods]]
modId = "cobblemon_quests_extended"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/WinterWolfSV/Cobblemon_Quests/master/neoforge/src/main/resources/META-INF/forge_mod_versions.json"
authors = ["WinterWolfSV"]
displayURL="https://modrinth.com/mod/cobblemon-quests/"
logoFile = "icon.png"
description = "${mod_description}"


[[dependencies.cobblemon_quests_extended]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_quests_extended]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"

[[dependencies.cobblemon_quests_extended]]
modId = "ftbquests"
mandatory = true
versionRange = "[2101.0.0,)"

[[dependencies.cobblemon_quests_extended]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.0,)"